import React, { useState } from "react";
import Link from "next/link";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";

import NavBar from "@/components/NavBar";
import SocialMedia from "@/components/SocialMedia";
import HomeIcons from "@/components/HomeIcons";
import SubNavBar from "@/components/SubNavBar";
import ProfileInfo from "@/components/ProfileInfo";
import Footer from "@/components/Footer";
import BookingBtn from "@/components/BookingBtn";
import Modal from "@/components/Modal"; // Import the Modal component
import { useState } from "react";

const Home = () => {

  const [darkMode, setDarkMode] = useState(false);
  const [showModal, setShowModal] = useState(true); // State to control modal visibility


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Milena Sports Massage Therapist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-milena-logo.png" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900">
        <section className="min-h-screen">
          <NavBar />

          {/* <SubNavBar /> */}

          {/* This is the SubNavBar */}
          <div className="py-20 mb-2 flex justify-between">
            <Link href="/">
              <h1 className="text-xl dark:text-white">Sports Massage Therapist</h1>
            </Link>

            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl dark:text-white"
                />
              </li>
            </ul>
          </div>


          <ProfileInfo />
          <BookingBtn />
          <SocialMedia />
        </section>

        <HomeIcons />
        <Footer darkMode={darkMode}/>

        {/* Modal Component */}
        <Modal showModal={showModal} setShowModal={setShowModal} />

      </main>
    </div>
  );
};

export default Home;
