import Head from "next/head";

import NavBar from "@/components/NavBar";
import SocialMedia from "@/components/SocialMedia";
import HomeIcons from "@/components/HomeIcons";
import SubNavBar from "@/components/SubNavBar";
import ProfileInfo from "@/components/ProfileInfo";
import Footer from "@/components/Footer";
import BookingBtn from "@/components/BookingBtn";

const Home = () => {
  return (
    <>
      <Head>
        <title>Milena Sports Massage Therapist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <NavBar />
          <SubNavBar />
          <ProfileInfo />
          <BookingBtn />
          <SocialMedia />
        </section>

        <section className="min-h-screen">
          <HomeIcons />
          <Footer />
        </section>
      </main>
    </>
  );
};

export default Home;
